### ISSUE TITLE
Slow reload/shutdown

### ISSUE THREAD

**Issue by gbjtv** [mailru/graphite-nginx-module#14]
Is it expected for the nginx workers to take longer to shutdown/reload when this module is compiled in + enabled? We've noticed the shutdown/reload process is significantly longer when enabled even when completely idle. 

These are the config lines we have:
```
graphite_config server=graphite.domain.com prefix=stats.counters.tier1 frequency=10;
graphite_data nginx.location.slash
```

**Comment by kirimedia** [comment]
During restart nginx waits until all requests and timers are completed.
The graphite module sets the timer to send data. The frequency of this timer is set in the parameter "frequency".
I could break the timer interval into smaller intervals and check for reload signal more frequently.
Is this issue critial for you?

**Comment by gbjtv** [comment]
I just happen to find it while trying to debug a segfault issue with another nginx module in a vagrant with very low memory available. By no means is it critical for us. Thanks!
