### ISSUE TITLE
What is supposed to happen in when graphite_default_data's $location is used with the root location?

### ISSUE THREAD

**Issue by tareq-khandaker-ck-xx** [mailru/graphite-nginx-module#21]
The documentation (https://github.com/mailru/graphite-nginx-module#graphite_default_data) says that:
> Data for `/foo/` will be sent to `nginx.foo`, data for `/bar/` - to `nginx.bar`

What is supposed to happen to the data for `/` with `graphite_default_data nginx.$location;`?

**Comment by kirimedia** [comment]
These data will not collected.
You need to add a separate graphite_data for the location `/`.
