### ISSUE TITLE
Does not connect to graphite

### ISSUE THREAD

**Issue by EricByers** [mailru/graphite-nginx-module#3]
Was having issues before with 1.0.3 and adding the patches, but with 1.0.4 that has been resolved for me now.

However it doesn't seem like it will connect to graphite, no errors in my logs, and using `tcpdump` on port 2003 shows nothing happening.  Let me know if I can provide any additional information to debug.  Thank you.

**Comment by kirimedia** [comment]
Check the configuration directives graphite_config and graphite_data. The first package will be sent to graphite only through 60s.

**Comment by EricByers** [comment]
I was using 1.8.0, but upgrading to 1.9.2 and still seeing issues, perhaps an issue with other modules?

My http blocks looks like

```
http {
    graphite_config prefix=nginx server=my.graphite.ip.here;
}
```

And my location block

```
location ^~ /foo/ {
    graphite_data nginx.foo;
}
```

Here is my configuration block (this is configuring 1.9.2 from source)

```
./configure --user=nginx --group=nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --add-module=/path/to/lua-nginx-module-0.9.16 --with-select_module --with-poll_module --with-file-aio --with-http_ssl_module --with-http_spdy_module --with-http_realip_module --with-http_addition_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-cpp_test_module  --with-cpu-opt=CPU --with-pcre  --with-pcre-jit  --with-md5-asm  --with-sha1-asm  --with-zlib-asm=CPU --with-libatomic --with-debug --with-ld-opt="-Wl,-E,-rpath,/usr/local/lib" --add-module=/path/to/ngx_devel_kit-0.2.19/ --add-module=/path/to/nginx-rtmp-module-1.1.7/ --add-module=/path/to/form-input-nginx-module-0.11/ --add-module=/path/to/nginx-module-vts-0.1.1/ --add-module=/path/to/graphite-nginx-module-1.0.4
```

Even with error_log on debug I can't see any output or information of why it is not sending.

Edit: I didn't note it here, but both patches were added (to lua using `lua_module_v0_9_11.patch` and nginx using `graphite_module_v1_7_7.patch`)

**Comment by EricByers** [comment]
I was using tcpdump to monitor this before, but specifically on tcp, just checked up and the data appears to be sending, so this looks like an issue internally, thanks for your help (and for the module)!
