### ISSUE TITLE
empty prefix

### ISSUE THREAD

**Issue by tarasbikhanov** [mailru/graphite-nginx-module#7]
Is it possible to use empty prefix in graphite_config?
If i set prefix='' i have ''.hostname.nginx... in graphite.

**Comment by kirimedia** [comment]
Not now. I will add this feature in the near future.

**Comment by kirimedia** [comment]
Now you can not set the parameter prefix.
Also, you can control the name of the graph using the template parameter.
The default value is $prefix.$host.$split.$param.$name_$interval

**Comment by tarasbikhanov** [comment]
template dowsnt work.
I compile nginx with new version of module and have error:
 # nginx -t
nginx: [error] graphite unknow template arg param in /usr/local/nginx/conf/nginx.conf:51
nginx: [error] graphite invalid option value template=$prefix.$host.$split.$param_$interval in /usr/local/nginx/conf/nginx.conf:51
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed

String in config i copy from readme
graphite_config prefix=playground server=127.0.0.1 intervals=1m|5m|15m params=rps|request_time|upstream_time template=$prefix.$host.$split.$param_$interval;

**Comment by kirimedia** [comment]
I mixed up the name of the parameter. I fixed it. Should work.
