### ISSUE TITLE
Error compiling with nginx 1.9.11+

### ISSUE THREAD

**Issue by EricByers** [mailru/graphite-nginx-module#8]
It looks like lua-nginx-module had to do some updates to work with the nginx 1.9.11+, and it looks to have broken a few items with this module.

https://github.com/openresty/lua-nginx-module/releases/tag/v0.10.1rc1
https://github.com/openresty/lua-nginx-module/releases/tag/v0.10.1rc0

I was using 1.9.12, but same issue on 1.9.11

Lua Module Patch

```
patching file config
Hunk #1 FAILED at 254.
Hunk #2 FAILED at 307.
2 out of 2 hunks FAILED -- saving rejects to file config.rej
```

Graphite Patch

```
patching file src/ngx_http_lua_graphite.c
patching file src/ngx_http_lua_graphite.h
patching file src/ngx_http_lua_util.c
Hunk #1 succeeded at 51 with fuzz 2 (offset 1 line).
Hunk #2 FAILED at 685.
Hunk #3 succeeded at 754 (offset 35 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/ngx_http_lua_util.c.rej
```

**Comment by kirimedia** [comment]
I add lua_module_v0_9_20.patch for lua module version >= 0.9.20

**Comment by EricByers** [comment]
Thanks!  

As a side note, this looks like it works under nginx-lua rc0, but they made a bunch of config changes in rc1, so the patch fails to apply those.  But working under rc0 of the lua module.

**Comment by kirimedia** [comment]
I will add a patch to 0.10.1 when the stable version is released.

**Comment by EricByers** [comment]
Looks like 10.1 (and now 10.2) are released: https://github.com/openresty/lua-nginx-module/releases

**Comment by red61wjt** [comment]
I am currently on holiday until May 4th

If you require support, please email support@red61.com

Alternatively I will respond to your email upon my return

Will Tatam

**Comment by kirimedia** [comment]
I will add patches tomorrow.

**Comment by kirimedia** [comment]
I added lua_module_v0_10_2.patch for versions >= 0.10.2
For 0.10.1 works patch lua_module_v0.9.20.patch
