### ISSUE TITLE
Can't use ngx.graphite() function to send metric data

### ISSUE THREAD

**Issue by redice** [mailru/graphite-nginx-module#9]
I failed to write ngx.graphite() function to send metric data. Could you give me some guide to solve it, thanks.

My environment is below
# /usr/local/nginx/sbin/nginx -V

nginx version: nginx/1.10.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
built with OpenSSL 1.0.1s  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_sub_module --with-http_flv_module --with-http_gzip_static_module --with-http_gunzip_module --with-http_secure_link_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-ipv6 --with-http_dav_module --with-debug --with-stream --with-stream_ssl_module --with-openssl=../openssl-1.0.1s --add-module=../ngx_cache_purge-2.3 --add-module=../echo-nginx-module-0.58 --add-module=../nginx-http-auth-digest-master --with-ld-opt='-Wl,-rpath,/usr/local/luajit/lib /usr/local/src/gc.lua/mydata.o' --add-dynamic-module=../ngx_devel_kit-0.3.0 --add-dynamic-module=../lua-nginx-module-0.10.6 --add-dynamic-module=../graphite-nginx-module-1.1.0

nginx.conf

location /code {
        graphite_param name=lua.abc aggregate=sum interval=10s;
        content_by_lua_block {
            ngx.graphite("lua.abc", 0.01)
            ngx.say("hello")
        }
    }

Error messages below:
2016/09/22 18:44:22 [debug] 1879#0: *1 lua run thread, top:0 c:1
2016/09/22 18:44:22 [debug] 1879#0: *1 lua resume returned 2
2016/09/22 18:44:22 [error] 1879#0: *1 lua entry thread aborted: runtime error: content_by_lua(rick.conf:100):2: attempt to call field 'graphite' (a nil value)
stack traceback:
coroutine 0:

**Comment by kirimedia** [comment]
To use ngx.graphite function you must apply a patch to the lua module.
Use this instruction to build https://github.com/mailru/graphite-nginx-module#build-nginx-with-lua-and-graphite-modules

**Comment by redice** [comment]
Thanks for your README file.
It works well in lua-nginx-module-0.10.2 after merge lua_module_v0_10_2.patch.
But can't work in lua-nginx-module-0.10.6, is it correct?
Thanks.

**Comment by kirimedia** [comment]
I have added a patch to lua module version> = 0.10.6
https://github.com/mailru/graphite-nginx-module/blob/master/lua_module_v0_10_6.patch

**Comment by redice** [comment]
Thanks for your quick replay. I try it.
It works. Thank you very much

**Comment by redice** [comment]
One more question
I try to pass nginx variable to graphite-nginx module, but it's failed to read nginx variable.
Does current graphite-nginx support nginx variable?
Thanks.

```
server_name  test_rick_idv;
location /code {
        graphite_data nginx.$http_host.code;
        proxy_pass   http://xxx/code;
    }
```

Graphite metric data is

```
xxx.nginx.$http_host.code.rps
```

But I expect the result like

```
xxx.nginx.test_rick_idv.code.rps
```

**Comment by kirimedia** [comment]
No. graphite_data not support variables, as in the configuration step is necessary to know the names of all metrics. But you can use "if".

```
map $http_host $http_host_a { host_a 1; }
map $http_host $http_host_b { host_b 1; }
```

```
location /code {
    graphite_data nginx.host_a.code if=$http_host_a;
    graphite_data nginx.host_b.code if=$http_host_b;
    ...
}
```

**Comment by redice** [comment]
Understood, thanks.

Bests regards,
Rick
